filebeat.inputs:
  - type: container
    paths:
      - "/var/lib/docker/containers/*/*.log"
#    json.keys_under_root: true
#    json.add_error_key: true
    processors:
      - add_docker_metadata: ~
      - add_host_metadata: ~
      - dissect:
          tokenizer: "%{container.id}-%{container.name}"
          field: "container.name"
          target_prefix: "container_info"


output.elasticsearch:
  hosts: ["http://stack.elk.io:9200"]
  username: "elastic"
  password: "wE+8UcT8=m66toF718b6"
  allow_older_versions: true

setup.kibana:
  host: "https://stack.elk.io"

setup.ilm.enabled: false

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
