apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      format json
    </source>

    <match **>
      @type elasticsearch
      host elasticsearch-host
      port 9200
      logstash_format true
      logstash_prefix kubernetes-logs
    </match>
